
AIST_proc() {
  local Name0=$(echo "$3" | sed -r "s|^.*/.*\[@(.*)=\".*\".*$|\1|")
  local Value0=$(echo "$3" | sed -r "s|^.*/.*\[@.*=\"(.*)\".*$|\1|")
  [ "$(echo "$4" | grep '=')" ] && Name1=$(echo "$4" | sed "s|=.*||") || local Name1="value"
  local Value1=$(echo "$4" | sed "s|.*=||")
  case $1 in
  "-s"|"-u"|"-i")
    local SNP=$(echo "$3" | sed -r "s|(^.*/.*)\[@.*=\".*\".*$|\1|")
    local NP=$(dirname "$SNP")
    local SN=$(basename "$SNP")
	if [ "$5" ]; then
      [ "$(echo "$5" | grep '=')" ] && local Name2=$(echo "$5" | sed "s|=.*||") || local Name2="value"
      local Value2=$(echo "$5" | sed "s|.*=||")
	fi
	if [ "$6" ]; then
      [ "$(echo "$6" | grep '=')" ] && local Name3=$(echo "$6" | sed "s|=.*||") || local Name3="value"
      local Value3=$(echo "$6" | sed "s|.*=||")
	fi
	if [ "$7" ]; then
      [ "$(echo "$7" | grep '=')" ] && local Name4=$(echo "$7" | sed "s|=.*||") || local Name4="value"
      local Value4=$(echo "$7" | sed "s|.*=||")
	fi
  ;;
  esac
  case "$1" in
    "-d") xmlstarlet ed -L -d "$3" "$2";;
    "-u") xmlstarlet ed -L -u "$3/@$Name1" -v "$Value1" "$2";;
    "-s")
  	if [ "$(xmlstarlet sel -t -m "$3" -c . "$2")" ]; then
        xmlstarlet ed -L -u "$3/@$Name1" -v "$Value1" "$2"
      else
        xmlstarlet ed -L -s "$NP" -t elem -n "$SN-$MODID" \
        -i "$SNP-$MODID" -t attr -n "$Name0" -v "$Value0" \
        -i "$SNP-$MODID" -t attr -n "$Name1" -v "$Value1" \
        -r "$SNP-$MODID" -v "$SN" "$2"
  	fi;;
    "-i")
  	if [ "$(xmlstarlet sel -t -m "$3[@$Name1=\"$Value1\"]" -c . "$2")" ]; then
        xmlstarlet ed -L -d "$3[@$Name1=\"$Value1\"]" "$2"
  	fi
  	if [ -z "$Value3" ]; then
        xmlstarlet ed -L -s "$NP" -t elem -n "$SN-$MODID" \
        -i "$SNP-$MODID" -t attr -n "$Name0" -v "$Value0" \
        -i "$SNP-$MODID" -t attr -n "$Name1" -v "$Value1" \
        -i "$SNP-$MODID" -t attr -n "$Name2" -v "$Value2" \
        -r "$SNP-$MODID" -v "$SN" "$2"
      elif [ "$Value4" ]; then
        xmlstarlet ed -L -s "$NP" -t elem -n "$SN-$MODID" \
        -i "$SNP-$MODID" -t attr -n "$Name0" -v "$Value0" \
        -i "$SNP-$MODID" -t attr -n "$Name1" -v "$Value1" \
        -i "$SNP-$MODID" -t attr -n "$Name2" -v "$Value2" \
        -i "$SNP-$MODID" -t attr -n "$Name3" -v "$Value3" \
        -i "$SNP-$MODID" -t attr -n "$Name4" -v "$Value4" \
        -r "$SNP-$MODID" -v "$SN" "$2"
      elif [ "$Value3" ]; then
        xmlstarlet ed -L -s "$NP" -t elem -n "$SN-$MODID" \
        -i "$SNP-$MODID" -t attr -n "$Name0" -v "$Value0" \
        -i "$SNP-$MODID" -t attr -n "$Name1" -v "$Value1" \
        -i "$SNP-$MODID" -t attr -n "$Name2" -v "$Value2" \
        -i "$SNP-$MODID" -t attr -n "$Name3" -v "$Value3" \
        -r "$SNP-$MODID" -v "$SN" "$2"
  	fi
      ;;
  esac
}

[ -f /system/vendor/build.prop ] && BUILDS="/system/build.prop /system/vendor/build.prop" || BUILDS="/system/build.prop"
SD617=$(grep "ro.board.platform=msm8952" $BUILDS)
SD625=$(grep "ro.board.platform=msm8953" $BUILDS)
SD660=$(grep "ro.board.platform=sdm660" $BUILDS)
SD662=$(grep "ro.board.platform=bengal" $BUILDS)
SD665=$(grep "ro.board.platform=trinket" $BUILDS)
SD670=$(grep "ro.board.platform=sdm670" $BUILDS)
SD710=$(grep "ro.board.platform=sdm710" $BUILDS)
SD720G=$(grep "ro.board.platform=atoll" $BUILDS)
SD730G=$(grep "ro.board.platform=sm6150" $BUILDS)
SD765G=$(grep "ro.board.platform=lito" $BUILDS)
SD820=$(grep "ro.board.platform=msm8996" $BUILDS)
SD835=$(grep "ro.board.platform=msm8998" $BUILDS)
SD845=$(grep "ro.board.platform=sdm845" $BUILDS)
SD855=$(grep "ro.board.platform=msmnile" $BUILDS)
SD865=$(grep "ro.board.platform=kona" $BUILDS)
SD888=$(grep "ro.board.platform=lahaina" $BUILDS)
SM8450=$(grep "ro.board.platform=taro" $BUILDS)

if [ "$SD662" ] || [ "$SD665" ] || [ "$SD670" ] || [ "$SD710" ] || [ "$SD720G" ] || [ "$SD730G" ] || [ "$SD765G" ] || [ "$SD820" ] || [ "$SD835" ] || [ "$SD845" ] || [ "$SD855" ] || [ "$SD865" ] || [ "$SD888" ] || [ "$SM8450" ]; then
  HIFI=true
ui_print " "
ui_print "- Device with support Hi-Fi detected! -"
else
  NOHIFI=false
ui_print " "
ui_print " - Device without support Hi-Fi detected! -"
fi

RN5PRO=$(grep -E "ro.product.vendor.device=whyred.*" $BUILDS)
RN6PRO=$(grep -E "ro.product.vendor.device=tulip.*" $BUILDS)
RN7=$(grep -E "ro.product.vendor.device=lavender.*" $BUILDS)
RN7PRO=$(grep -E "ro.product.vendor.device=violet.*" $BUILDS)
MI9=$(grep -E "ro.product.vendor.device=cepheus.*" $BUILDS)
MI10=$(grep -E "ro.product.vendor.device=umi.*" $BUILDS)
K20P=$(grep -E "ro.product.vendor.device=raphael.*|ro.product.vendor.device=raphaelin.*|ro.product.vendor.device=raphaels.*" $BUILDS)
MI8=$(grep -E "ro.product.vendor.device=dipper.*" $BUILDS)
MI8P=$(grep -E "ro.product.vendor.device=equuleus.*" $BUILDS)
MI9P=$(grep -E "ro.product.vendor.device=crux.*" $BUILDS)
POCOF1=$(grep -E "ro.product.vendor.device=beryllium.*" $BUILDS)
POCOF2P=$(grep -E "ro.product.vendor.device=lmi.*" $BUILDS)
MPATHS="$(find /system /vendor /system_ext /product /odm -type f -name "*mixer_paths*.xml")"
APINF="$(find /system /vendor /system_ext /product /odm -type f -name "audio_platform_info*.xml")"
ACONFS="$(find /system /vendor /system_ext /product /odm -type f -name "audio_configs*.xml")"
APCXML="$(find /system /vendor /system_ext /product /odm -type f -name "audio_policy_configuration*.xml")"
LOG=$MODPATH/common/other

mkdir -p $MODPATH/tools
cp -f $MODPATH/common/addon/External-Tools/tools/$ARCH32/* $MODPATH/tools/

  for OMIX in ${MPATHS}; do
	MIX="$MODPATH$(echo $OMIX | sed "s|^/vendor|/system/vendor|g")"
	cp_ch $ORIGDIR$OMIX $MIX
	sed -i 's/\t/  /g' $MIX
	done

ui_print " "
ui_print " - Improve Volume Levels -"
  ui_print "***************************************************"
  ui_print "*                                                 *"
  ui_print "*  Volume boost for those who lack the volume of  *"
  ui_print "*            speakers and microphones!            *"
  ui_print "*       Be careful when listening to music        *"
  ui_print "*               at maximum volume!                *"
  ui_print "*                                                 *"
  ui_print "***************************************************"
  ui_print "*                                                 *"
  ui_print "*      Installation time of this item ≈1 min      *"
  ui_print "*                                                 *"
  ui_print "***************************************************"
ui_print "   Improve Volume Levels?"
ui_print " "

sleep 1
ui_print "   Vol Up = YES, Vol Down = NO"
ui_print " "

if $VKSEL; then

ui_print " - Installing Improve Volume Levels -"
ui_print " -          Please, wait...         -"

  for OMIX in ${MPATHS}; do
	MIX="$MODPATH$(echo $OMIX | sed "s|^/vendor|/system/vendor|g")"
	if ! $NOHIFI; then
	AIST_proc -u $MIX '/mixer/ctl[@name="RX0 Digital Volume"]' "86"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX4 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX5 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX6 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX7 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX8 Digital Volume"]' "90"
	AIST_proc -s $MIX '/mixer/ctl[@name="RX8 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="WSA_RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="WSA_RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="WSA_RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="WSA_RX3 Digital Volume"]' "90"
	AIST_proc -s $MIX '/mixer/ctl[@name="WSA_RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX_RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX_RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX_RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX_RX3 Digital Volume"]' "90"
	AIST_proc -s $MIX '/mixer/ctl[@name="RX_RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC0 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC1 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC2 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC3 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC4 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC5 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC6 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC7 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC8 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC0 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC1 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC2 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC3 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC4 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC5 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC6 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC7 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC8 Volume"]' "94"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX_RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX_RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX_RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX_RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX4 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX5 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX6 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX7 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX8 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="WSA_RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="WSA_RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="WSA_RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="WSA_RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="LINEOUT1 Volume"]' "16"
	AIST_proc -u $MIX '/mixer/ctl[@name="LINEOUT2 Volume"]' "16"
	elif $HIFI; then
	AIST_proc -u $MIX '/mixer/ctl[@name="RX0 Digital Volume"]' "86"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX4 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX5 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX6 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX7 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX8 Digital Volume"]' "90"
	AIST_proc -s $MIX '/mixer/ctl[@name="RX8 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="WSA_RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="WSA_RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="WSA_RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="WSA_RX3 Digital Volume"]' "90"
	AIST_proc -s $MIX '/mixer/ctl[@name="WSA_RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX_RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX_RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX_RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX_RX3 Digital Volume"]' "90"
	AIST_proc -s $MIX '/mixer/ctl[@name="RX_RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC0 Volume"]' "88"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC1 Volume"]' "88"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC2 Volume"]' "88"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC3 Volume"]' "88"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC4 Volume"]' "86"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC5 Volume"]' "86"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC6 Volume"]' "86"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC7 Volume"]' "86"
	AIST_proc -u $MIX '/mixer/ctl[@name="DEC8 Volume"]' "86"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC0 Volume"]' "88"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC1 Volume"]' "88"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC2 Volume"]' "88"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC3 Volume"]' "88"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC4 Volume"]' "86"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC5 Volume"]' "86"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC6 Volume"]' "86"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC7 Volume"]' "86"
	AIST_proc -u $MIX '/mixer/ctl[@name="TX_DEC8 Volume"]' "86"
	AIST_proc -u $MIX '/mixer/ctl[@name="VA_DEC0 Volume"]' "88"
	AIST_proc -u $MIX '/mixer/ctl[@name="VA_DEC1 Volume"]' "88"
	AIST_proc -u $MIX '/mixer/ctl[@name="VA_DEC2 Volume"]' "88"
	AIST_proc -u $MIX '/mixer/ctl[@name="VA_DEC3 Volume"]' "88"
	AIST_proc -u $MIX '/mixer/ctl[@name="VA_DEC4 Volume"]' "86"
	AIST_proc -u $MIX '/mixer/ctl[@name="VA_DEC5 Volume"]' "86"
	AIST_proc -u $MIX '/mixer/ctl[@name="VA_DEC6 Volume"]' "86"
	AIST_proc -u $MIX '/mixer/ctl[@name="VA_DEC7 Volume"]' "86"
	AIST_proc -u $MIX '/mixer/ctl[@name="VA_DEC8 Volume"]' "86"
	AIST_proc -u $MIX '/mixer/path[@name="headset-mic"]/ctl[@name="TX_DEC0 Volume"]' "88"
	AIST_proc -u $MIX '/mixer/path[@name="voice-tty-full-headset-mic"]/ctl[@name="TX_DEC5 Volume"]' "88"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX_RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX_RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX_RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX_RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX4 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX5 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX6 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX7 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX8 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="WSA_RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="WSA_RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="WSA_RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="WSA_RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX_RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX_RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX_RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX_RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX4 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX5 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX6 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX7 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX8 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="WSA_RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="WSA_RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="WSA_RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="WSA_RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX_RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX_RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX_RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX_RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX4 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX5 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX6 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX7 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX8 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="WSA_RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="WSA_RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="WSA_RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="WSA_RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="RX_RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="RX_RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="RX_RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="RX_RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="RX4 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="RX5 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="RX6 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="RX7 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="RX8 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="WSA_RX0 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="WSA_RX1 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="WSA_RX2 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="WSA_RX3 Digital Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="LINEOUT1 Volume"]' "16"
	AIST_proc -u $MIX '/mixer/ctl[@name="LINEOUT2 Volume"]' "16"
	fi
	done
fi

ui_print " "
ui_print " - Install Dolby Atmos Preset's Feature -"
  ui_print "***************************************************"
  ui_print "*                                                 *"
  ui_print "*      This tweak enable Dolby Atmos Preset's     *"
  ui_print "*          Doesn't work on all firmwares          *"
  ui_print "*    Cause sound driver crash on some firmware    *"
  ui_print "*                                                 *"
  ui_print "***************************************************"
ui_print "   Install Dolby Atmos Preset's Feature?"
ui_print " "
sleep 1
ui_print "   Vol Up = YES, Vol Down = NO"
ui_print " " 

if $VKSEL; then

ui_print " - Installing Dolby Atmos Preset's Feature -"

	prop_process $MODPATH/common/DAP.prop
fi

ui_print " "
ui_print " - Disable Dolby Vision -"
  ui_print "***************************************************"
  ui_print "*                                                 *"
  ui_print "*         This tweak Disable Dolby Vision         *"
  ui_print "*          Doesn't work on all firmwares          *"
  ui_print "*      Reduce stereo enhance making the sound     *"
  ui_print "*      more natural. Improved bass and treble     *"
  ui_print "*                                                 *"
  ui_print "***************************************************"
ui_print "   Disable Dolby Vision?"
ui_print " "
sleep 1
ui_print "   Vol Up = YES, Vol Down = NO"
ui_print " " 

if $VKSEL; then

ui_print " - Disabling Dolby Vision -"

	prop_process $MODPATH/common/DVOFF.prop
fi

ui_print " "
ui_print " - Install Other Tweaks -"
  ui_print "***************************************************"
  ui_print "*                                                 *"
  ui_print "*                 !!!Attention!!!                 *"
  ui_print "*    Various tweaks not related to sound that     *"
  ui_print "*                I added for myself               *"
  ui_print "*                                                 *"
  ui_print "***************************************************"
ui_print "   Install Other Tweaks?"
ui_print " "
sleep 1
ui_print "   Vol Up = YES, Vol Down = NO"
ui_print " " 

if $VKSEL; then

ui_print " - Installing Other Tweaks -"

	prop_process $MODPATH/common/other.prop
	cp_ch $LOG/cnss_diag $MODPATH/system/bin/cnss_diag
	cp_ch $LOG/logd $MODPATH/system/bin/logd
	cp_ch $LOG/tcpdump $MODPATH/system/bin/tcpdump
	cp_ch $LOG/cnss_diag $MODPATH/system/vendor/bin/cnss_diag
	cp_ch $LOG/logd $MODPATH/system/vendor/bin/logd
	cp_ch $LOG/tcpdump $MODPATH/system/vendor/bin/tcpdump
	cp_ch $LOG/logd.rc $MODPATH/system/etc/init/logd.rc
	cp_ch $LOG/logd.rc $MODPATH/system/vendor/etc/init/logd.rc
	cp_ch $LOG/logwrapper $MODPATH/system/bin/logwrapper
	cp_ch $LOG/logwrapper $MODPATH/system/vendor/bin/logwrapper
	cp_ch $LOG/atrace $MODPATH/system/bin/atrace
	cp_ch $LOG/atrace $MODPATH/system/vendor/bin/atrace
	cp_ch $LOG/logd.rc $MODPATH/system/etc/init/atrace.rc
	cp_ch $LOG/logd.rc $MODPATH/system/vendor/etc/init/atrace.rc
	cp_ch $LOG/Traceur.apk $MODPATH/system/app/Traceur/Traceur.apk
	cp_ch $LOG/Traceur.apk $MODPATH/system/vendor/app/Traceur/Traceur.apk
	cp_ch $LOG/Traceur.apk $MODPATH/system/priv-app/Traceur/Traceur.apk
	cp_ch $LOG/Traceur.apk $MODPATH/system/vendor/priv-app/Traceur/Traceur.apk
fi

ui_print " "
ui_print " - Installing Main Patches -"
  ui_print "***************************************************"
  ui_print "*                                                 *"
  ui_print "*          General changes for all devices.       *"
  ui_print "*  Including maximum sound quality, bass booster, *"
  ui_print "*       Hi-Fi support, Dolby Surround, etc.       *"
  ui_print "*                                                 *"
  ui_print "***************************************************"
  ui_print "*                                                 *"
  ui_print "*      Installation time of this item ≈5 min      *"
  ui_print "*                 Please, wait...                 *"
  ui_print "*                                                 *"
  ui_print "***************************************************"

  for OMIX in ${MPATHS}; do
	MIX="$MODPATH$(echo $OMIX | sed "s|^/vendor|/system/vendor|g")"
	if ! $NOHIFI; then
	AIST_proc -s $MIX '/mixer/ctl[@name="RX_HPH_PWR_MODE"]' "HIRES"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX HPH Mode"]' "HD2"
	AIST_proc -s $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX_HPH_PWR_MODE"]' "HIRES"
	AIST_proc -s $MIX '/mixer/ctl[@name="VBoost Ctrl"]' "AlwaysOn"
	AIST_proc -u $MIX '/mixer/ctl[@name="HPHL"]' "Switch"
	AIST_proc -u $MIX '/mixer/ctl[@name="HPHR"]' "Switch"
	AIST_proc -u $MIX '/mixer/ctl[@name="Load acoustic model"]' "1"
	elif $HIFI; then
	AIST_proc -u $MIX '/mixer/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -s $MIX '/mixer/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="speaker"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="top-speaker"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="top-speaker"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="bottom-speaker"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="bottom-speaker"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="hph-hifi-mode"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="hph-hifi-mode"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="hph-highquality-mode"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="hph-highquality-mode"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="hph-lowpower-mode"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="hph-lowpower-mode"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="hph-class-ab-mode"]/ctl[@name="RX HPH Mode"]' "CLS_AB_HIFI"
	AIST_proc -s $MIX '/mixer/path[@name="hph-class-ab-mode"]/ctl[@name="RX HPH Mode"]' "CLS_AB_HIFI"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headset"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="voice-headset"]/ctl[@name="RX HPH Mode"]' "CLS_H_LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="speaker"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="top-speaker"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="top-speaker"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="bottom-speaker"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="bottom-speaker"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="hph-hifi-mode"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="hph-hifi-mode"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="hph-highquality-mode"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="hph-highquality-mode"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="hph-lowpower-mode"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="hph-lowpower-mode"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headset"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	AIST_proc -s $MIX '/mixer/path[@name="voice-headset"]/ctl[@name="RX_HPH_PWR_MODE"]' "LOHIFI"
	fi
	AIST_proc -u $MIX '/mixer/ctl[@name="Voice Sidetone Enable"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="MSM ASphere Set Param"]' "0"
	AIST_proc -s $MIX '/mixer/ctl[@name="MSM ASphere Set Param"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="Codec Wideband"]' "0"
	AIST_proc -s $MIX '/mixer/ctl[@name="Codec Wideband"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="Set Custom Stereo OnOff"]' "0"
	AIST_proc -s $MIX '/mixer/ctl[@name="Set Custom Stereo OnOff"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="HiFi Function"]' "On"
	AIST_proc -s $MIX '/mixer/ctl[@name="HiFi Function"]' "On"
	AIST_proc -u $MIX '/mixer/ctl[@name="Custom Filter"]' "ON"
	AIST_proc -s $MIX '/mixer/ctl[@name="Custom Filter"]' "ON"
	AIST_proc -u $MIX '/mixer/ctl[@name="Filter Shape"]' "Slow Rolloff"
	AIST_proc -s $MIX '/mixer/ctl[@name="Filter Shape"]' "Slow Rolloff"
	AIST_proc -u $MIX '/mixer/ctl[@name="EC Reference Bit Format"]' "S24_LE"
	AIST_proc -u $MIX '/mixer/ctl[@name="SpkrLeft BOOST Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SpkrRight BOOST Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SpkrLeft VISENSE Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SpkrRight VISENSE Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SpkrLeft SWR DAC_Port Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SpkrRight SWR DAC_Port Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="ANC OUT HPHL Enable Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="ANC OUT HPHR Enable Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="BDE Enable"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="BDE AMP Enable"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="BDE Enable"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="BDE AMP Enable"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="Amp DSP Enable"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="Amp DSP Enable"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="DRE En"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="DRE En"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="RCV DRE DRE Switch"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="RCV DRE DRE Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="DRE DRE Switch"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="DRE DRE Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="Virtual Bass Boost"]' "On"
	AIST_proc -s $MIX '/mixer/ctl[@name="Virtual Bass Boost"]' "On"
	AIST_proc -s $MIX '/mixer/ctl[@name="WSA_RX0 EC_HQ Switch"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="WSA_RX1 EC_HQ Switch"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="WSA_RX3 EC_HQ Switch"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="WSA_RX4 EC_HQ Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX INT1 SEC MIX HPHL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX INT2 SEC MIX HPHR Switch"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="RX INT3 SEC MIX LO1 Switch"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="RX INT4 SEC MIX LO2 Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX INT1 MIX3 DSD HPHL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX INT2 MIX3 DSD HPHR Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX INT0 DEM MUX"]' "CLSH_DSM_OUT"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX INT1 DEM MUX"]' "CLSH_DSM_OUT"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX INT2 DEM MUX"]' "CLSH_DSM_OUT"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX INT3 DEM MUX"]' "CLSH_DSM_OUT"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX INT4 DEM MUX"]' "CLSH_DSM_OUT"
	AIST_proc -u $MIX '/mixer/ctl[@name="HPH Idle Detect"]' "ON"
	AIST_proc -s $MIX '/mixer/ctl[@name="HPH Idle Detect"]' "ON"
	AIST_proc -u $MIX '/mixer/ctl[@name="HPHL_RDAC Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="HPHR_RDAC Switch"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="A2DP_SLIM7_UL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="PCM_RX_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="USB_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="SLIM_7_RX Format"]' "S24_LE"
	AIST_proc -s $MIX '/mixer/ctl[@name="SLIM_7_RX SampleRate"]' "KHZ_192"
	AIST_proc -s $MIX '/mixer/ctl[@name="SLIM_7_RX Channels"]' "Two"
	AIST_proc -s $MIX '/mixer/ctl[@name="SLIMBUS_7_RX Format"]' "S24_LE"
	AIST_proc -s $MIX '/mixer/ctl[@name="SLIMBUS_7_RX SampleRate"]' "KHZ_192"
	AIST_proc -s $MIX '/mixer/ctl[@name="SLIMBUS_7_RX Channels"]' "Two"
	AIST_proc -s $MIX '/mixer/ctl[@name="SLIM7_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="A2DP_SLIM7_UL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="PCM_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="USB_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SLIM_7_RX Format"]' "S24_LE"
	AIST_proc -u $MIX '/mixer/ctl[@name="SLIM_7_RX SampleRate"]' "KHZ_192"
	AIST_proc -u $MIX '/mixer/ctl[@name="SLIM_7_RX Channels"]' "Two"
	AIST_proc -u $MIX '/mixer/ctl[@name="SLIMBUS_7_RX Format"]' "S24_LE"
	AIST_proc -u $MIX '/mixer/ctl[@name="SLIMBUS_7_RX SampleRate"]' "KHZ_192"
	AIST_proc -u $MIX '/mixer/ctl[@name="SLIMBUS_7_RX Channels"]' "Two"
	AIST_proc -u $MIX '/mixer/ctl[@name="SLIM7_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SLIM7_RX ADM Channels"]' "Two"
	AIST_proc -u $MIX '/mixer/ctl[@name="SCO_SLIM7_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="SCO_SLIM7_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="HFP_SLIM7_UL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="HFP_PRI_AUX_UL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="HFP_AUX_UL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="HFP_INT_UL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SLIMBUS_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SLIMBUS0_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SLIMBUS1_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SLIMBUS2_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SLIMBUS3_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SLIMBUS4_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SLIMBUS5_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SLIMBUS6_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SLIMBUS7_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="INT0_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="INT1_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="INT2_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="INT3_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="INT4_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="PRI_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SEC_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="TERT_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="QUAT_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="QUIN_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="SEN_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="WSA_CDC_DMA_RX_0_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX_CDC_DMA_RX_0_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX_CDC_DMA_RX_1_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="handset"]/ctl[@name="RCV Boost Class-H Tracking Enable"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="echo-reference a2dp"]/ctl[@name="EC Reference Bit Format"]' "S24_LE"
	AIST_proc -u $MIX '/mixer/path[@name="echo-reference a2dp"]/ctl[@name="EC Reference SampleRate"]' "96000"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-suspend"]/ctl[@name="Mi_Ultrasound Suspend"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-suspend"]/ctl[@name="Mi_Ultrasound Suspend"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-suspend"]/ctl[@name="Ultrasound Suspend"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-suspend"]/ctl[@name="Ultrasound Suspend"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS0_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS1_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS2_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS3_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS4_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS5_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS6_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS7_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="INT0_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="INT1_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="INT2_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="INT3_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="INT4_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="PRI_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SEC_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="TERT_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="QUAT_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="QUIN_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SEN_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="WSA_CDC_DMA_RX_0_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="WSA_CDC_DMA_RX_1_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="RX_CDC_DMA_RX_0_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="RX_CDC_DMA_RX_1_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="USB_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIM7_RX_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SCO_SLIM7_DL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="A2DP_SLIM7_UL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="HFP_SLIM7_UL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="HFP_PRI_AUX_UL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="HFP_AUX_UL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="HFP_INT_UL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS0_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS1_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS2_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS3_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS4_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS5_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS6_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIMBUS7_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="INT0_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="INT1_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="INT2_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="INT3_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="INT4_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="PRI_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SEC_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="TERT_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="QUAT_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="QUIN_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SEN_MI2S_RX_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="WSA_CDC_DMA_RX_0_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="WSA_CDC_DMA_RX_1_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="RX_CDC_DMA_RX_0_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="RX_CDC_DMA_RX_1_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="USB_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SLIM7_RX_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="SCO_SLIM7_DL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="A2DP_SLIM7_UL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="HFP_SLIM7_UL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="HFP_PRI_AUX_UL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="HFP_AUX_UL_HL Switch"]' "1"
	AIST_proc -s $MIX '/mixer/path[@name="ultrasound-proximity-output"]/ctl[@name="HFP_INT_UL_HL Switch"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="COMP3 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="COMP4 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="COMP5 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="COMP6 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="COMP7 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="COMP8 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="WSA_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="WSA_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="RX_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="SpkrLeft COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="SpkrRight COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="HPHL_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="HPHR_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="COMP3 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="COMP4 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="COMP5 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="COMP6 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="COMP7 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="COMP8 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="SpkrLeft COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="SpkrRight COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="WSA_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="WSA_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="RX_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="RX_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="HPHL_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-and-headphones"]/ctl[@name="HPHR_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="COMP3 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="COMP4 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="COMP5 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="COMP6 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="COMP7 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="COMP8 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="SpkrLeft COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="SpkrRight COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="WSA_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="WSA_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="RX_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="RX_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="HPHL_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker"]/ctl[@name="HPHR_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="COMP3 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="COMP4 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="COMP5 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="COMP6 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="COMP7 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="COMP8 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="SpkrLeft COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="SpkrRight COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="WSA_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="WSA_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="RX_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="RX_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="HPHL_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono"]/ctl[@name="HPHR_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="COMP3 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="COMP4 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="COMP5 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="COMP6 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="COMP7 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="COMP8 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="SpkrLeft COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="SpkrRight COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="WSA_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="WSA_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="RX_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="RX_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="HPHL_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="speaker-mono-2"]/ctl[@name="HPHR_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="handset"]/ctl[@name="COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="handset"]/ctl[@name="COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="handset"]/ctl[@name="COMP3 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="handset"]/ctl[@name="COMP4 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="handset"]/ctl[@name="COMP5 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="handset"]/ctl[@name="COMP6 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="handset"]/ctl[@name="COMP7 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="handset"]/ctl[@name="COMP8 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="handset"]/ctl[@name="SpkrLeft COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="handset"]/ctl[@name="SpkrRight COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="handset"]/ctl[@name="WSA_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="handset"]/ctl[@name="WSA_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="handset"]/ctl[@name="RX_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="handset"]/ctl[@name="RX_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="handset"]/ctl[@name="HPHL_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="handset"]/ctl[@name="HPHR_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="COMP3 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="COMP4 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="COMP5 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="COMP6 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="COMP7 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="COMP8 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="WSA_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="WSA_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="RX_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="HPHL_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones"]/ctl[@name="HPHR_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="COMP3 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="COMP4 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="COMP5 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="COMP6 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="COMP7 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="COMP8 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="WSA_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="WSA_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="RX_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="HPHL_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-44.1"]/ctl[@name="HPHR_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="COMP3 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="COMP4 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="COMP5 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="COMP6 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="COMP7 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="COMP8 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="WSA_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="WSA_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="RX_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="HPHL_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="headphones-dsd"]/ctl[@name="HPHR_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="COMP3 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="COMP4 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="COMP5 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="COMP6 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="COMP7 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="COMP8 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="SpkrLeft COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="SpkrRight COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="WSA_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="WSA_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="RX_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="RX_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="HPHL_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="anc-headphones"]/ctl[@name="HPHR_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headphones"]/ctl[@name="COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headphones"]/ctl[@name="COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headphones"]/ctl[@name="COMP3 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headphones"]/ctl[@name="COMP4 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headphones"]/ctl[@name="COMP5 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headphones"]/ctl[@name="COMP6 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headphones"]/ctl[@name="COMP7 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headphones"]/ctl[@name="COMP8 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headphones"]/ctl[@name="SpkrLeft COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headphones"]/ctl[@name="SpkrRight COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headphones"]/ctl[@name="WSA_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headphones"]/ctl[@name="WSA_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headphones"]/ctl[@name="RX_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headphones"]/ctl[@name="RX_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headphones"]/ctl[@name="HPHL_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="voice-headphones"]/ctl[@name="HPHR_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="tty-headphones"]/ctl[@name="COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="tty-headphones"]/ctl[@name="COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="tty-headphones"]/ctl[@name="COMP3 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="tty-headphones"]/ctl[@name="COMP4 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="tty-headphones"]/ctl[@name="COMP5 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="tty-headphones"]/ctl[@name="COMP6 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="tty-headphones"]/ctl[@name="COMP7 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="tty-headphones"]/ctl[@name="COMP8 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="tty-headphones"]/ctl[@name="SpkrLeft COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="tty-headphones"]/ctl[@name="SpkrRight COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="tty-headphones"]/ctl[@name="WSA_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="tty-headphones"]/ctl[@name="WSA_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="tty-headphones"]/ctl[@name="RX_COMP1 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="tty-headphones"]/ctl[@name="RX_COMP2 Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="tty-headphones"]/ctl[@name="HPHL_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/path[@name="tty-headphones"]/ctl[@name="HPHR_COMP Switch"]' "0"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band1"][@id="0"]' "268833620"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band1"][@id="1"]' "537398060"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band1"][@id="2"]' "267510580"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band1"][@id="3"]' "537398060"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band1"][@id="4"]' "267908744"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band2"][@id="0"]' "266468108"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band2"][@id="1"]' "544862876"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band2"][@id="2"]' "262421829"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band2"][@id="3"]' "544862876"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band2"][@id="4"]' "260454481"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band3"][@id="0"]' "262913321"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band3"][@id="1"]' "559557058"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band3"][@id="2"]' "252311547"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band3"][@id="3"]' "559557058"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band3"][@id="4"]' "246789412"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band4"][@id="0"]' "294517138"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band4"][@id="1"]' "572289454"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band4"][@id="2"]' "210943778"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band4"][@id="3"]' "572289454"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band4"][@id="4"]' "237025461"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band5"][@id="0"]' "329006442"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band5"][@id="1"]' "711929387"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band5"][@id="2"]' "110068469"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band5"][@id="3"]' "711929387"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Band5"][@id="4"]' "170639455"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Enable Band0"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Enable Band1"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Enable Band2"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Enable Band3"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Enable Band4"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 Enable Band5"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 INP0 Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 INP1 Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 INP2 Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 INP3 Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 INP4 Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR0 INP5 Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band1"][@id="0"]' "268833620"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band1"][@id="1"]' "537398060"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band1"][@id="2"]' "267510580"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band1"][@id="3"]' "537398060"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band1"][@id="4"]' "267908744"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band2"][@id="0"]' "266468108"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band2"][@id="1"]' "544862876"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band2"][@id="2"]' "262421829"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band2"][@id="3"]' "544862876"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band2"][@id="4"]' "260454481"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band3"][@id="0"]' "262913321"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band3"][@id="1"]' "559557058"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band3"][@id="2"]' "252311547"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band3"][@id="3"]' "559557058"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band3"][@id="4"]' "246789412"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band4"][@id="0"]' "294517138"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band4"][@id="1"]' "572289454"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band4"][@id="2"]' "210943778"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band4"][@id="3"]' "572289454"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band4"][@id="4"]' "237025461"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band5"][@id="0"]' "329006442"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band5"][@id="1"]' "711929387"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band5"][@id="2"]' "110068469"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band5"][@id="3"]' "711929387"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Band5"][@id="4"]' "170639455"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Enable Band0"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Enable Band1"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Enable Band2"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Enable Band3"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Enable Band4"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 Enable Band5"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 INP0 Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 INP1 Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 INP2 Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 INP3 Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 INP4 Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="IIR1 INP5 Volume"]' "90"
	AIST_proc -u $MIX '/mixer/ctl[@name="Cirrus SP Usecase"]' "Game"
	AIST_proc -s $MIX '/mixer/ctl[@name="Cirrus SP Usecase"]' "Game"
	AIST_proc -u $MIX '/mixer/ctl[@name="AUX_HPF Enable"]' "Off"
	AIST_proc -s $MIX '/mixer/ctl[@name="AUX_HPF Enable"]' "Off"
	AIST_proc -u $MIX '/mixer/ctl[@name="A2DP_HPF Enable"]' "Off"
	AIST_proc -s $MIX '/mixer/ctl[@name="A2DP_HPF Enable"]' "Off"
	AIST_proc -u $MIX '/mixer/ctl[@name="BT_HPF Enable"]' "Off"
	AIST_proc -s $MIX '/mixer/ctl[@name="BT_HPF Enable"]' "Off"
	AIST_proc -u $MIX '/mixer/ctl[@name="HPF Enable"]' "Off"
	AIST_proc -s $MIX '/mixer/ctl[@name="HPF Enable"]' "Off"
	AIST_proc -u $MIX '/mixer/ctl[@name="LDOH Enable"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="LDOH Enable"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="LPI Enable"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="LPI Enable"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="RCV Boost Class-H Tracking Enable"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="RCV Boost Class-H Tracking Enable"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="RCV AMP Enable"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="RCV AMP Enable"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="Boost Class-H Tracking Enable"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="Boost Class-H Tracking Enable"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="AMP Enable"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="AMP Enable"]' "1"
	AIST_proc -u $MIX '/mixer/ctl[@name="ST Enable"]' "1"
	AIST_proc -s $MIX '/mixer/ctl[@name="ST Enable"]' "1"
	done	

  for OAPLI in ${APINF}; do
	APLI="$MODPATH$(echo $OAPLI | sed "s|^/vendor|/system/vendor|g")"
	cp_ch $ORIGDIR$OAPLI $APLI
	sed -i 's/\t/  /g' $APLI
	AIST_proc -s $APLI '/audio_platform_info_intcodec/bit_width_configs/device[@name="SND_DEVICE_OUT_HEADPHONES"]' "24"
	AIST_proc -s $APLI '/audio_platform_info_intcodec/bit_width_configs/device[@name="SND_DEVICE_OUT_SPEAKER_REVERSE"]' "24"
	AIST_proc -s $APLI '/audio_platform_info_intcodec/bit_width_configs/device[@name="SND_DEVICE_OUT_SPEAKER_PROTECTED"]' "24"
	AIST_proc -s $APLI '/audio_platform_info_intcodec/bit_width_configs/device[@name="SND_DEVICE_OUT_HEADPHONES_44_1"]' "24"
	AIST_proc -s $APLI '/audio_platform_info_intcodec/bit_width_configs/device[@name="SND_DEVICE_OUT_GAME_SPEAKER"]' "24"
	AIST_proc -s $APLI '/audio_platform_info_intcodec/bit_width_configs/device[@name="SND_DEVICE_OUT_GAME_HEADPHONES"]' "24"
	AIST_proc -s $APLI '/audio_platform_info_intcodec/bit_width_configs/device[@name="SND_DEVICE_OUT_BT_A2DP"]' "24"
	AIST_proc -u $APLI '/audio_platform_info_intcodec/app_types/app[@mode="default"]' "bit_width=24"
	AIST_proc -u $APLI '/audio_platform_info_intcodec/app_types/app[@mode="default"]' "max_rate=192000"
	AIST_proc -s $APLI '/audio_platform_info_intcodec/app_types/app[@mode="default"]' "bit_width=24"
	AIST_proc -s $APLI '/audio_platform_info_intcodec/app_types/app[@mode="default"]' "max_rate=192000"
	AIST_proc -s $APLI '/audio_platform_info_extcodec/bit_width_configs/device[@name="SND_DEVICE_OUT_HEADPHONES"]' "24"
	AIST_proc -s $APLI '/audio_platform_info_extcodec/bit_width_configs/device[@name="SND_DEVICE_OUT_SPEAKER_REVERSE"]' "24"
	AIST_proc -s $APLI '/audio_platform_info_extcodec/bit_width_configs/device[@name="SND_DEVICE_OUT_SPEAKER_PROTECTED"]' "24"
	AIST_proc -s $APLI '/audio_platform_info_extcodec/bit_width_configs/device[@name="SND_DEVICE_OUT_HEADPHONES_44_1"]' "24"
	AIST_proc -s $APLI '/audio_platform_info_extcodec/bit_width_configs/device[@name="SND_DEVICE_OUT_GAME_SPEAKER"]' "24"
	AIST_proc -s $APLI '/audio_platform_info_extcodec/bit_width_configs/device[@name="SND_DEVICE_OUT_GAME_HEADPHONES"]' "24"
	AIST_proc -s $APLI '/audio_platform_info_extcodec/bit_width_configs/device[@name="SND_DEVICE_OUT_BT_A2DP"]' "24"
	AIST_proc -u $APLI '/audio_platform_info_extcodec/app_types/app[@mode="default"]' "bit_width=24"
	AIST_proc -u $APLI '/audio_platform_info_extcodec/app_types/app[@mode="default"]' "max_rate=192000"
	AIST_proc -s $APLI '/audio_platform_info_extcodec/app_types/app[@mode="default"]' "bit_width=24"
	AIST_proc -s $APLI '/audio_platform_info_extcodec/app_types/app[@mode="default"]' "max_rate=192000"
	AIST_proc -s $APLI '/audio_platform_info/bit_width_configs/device[@name="SND_DEVICE_OUT_HEADPHONES"]' "24"
	AIST_proc -s $APLI '/audio_platform_info/bit_width_configs/device[@name="SND_DEVICE_OUT_SPEAKER_REVERSE"]' "24"
	AIST_proc -s $APLI '/audio_platform_info/bit_width_configs/device[@name="SND_DEVICE_OUT_SPEAKER_PROTECTED"]' "24"
	AIST_proc -s $APLI '/audio_platform_info/bit_width_configs/device[@name="SND_DEVICE_OUT_HEADPHONES_44_1"]' "24"
	AIST_proc -s $APLI '/audio_platform_info/bit_width_configs/device[@name="SND_DEVICE_OUT_GAME_SPEAKER"]' "24"
	AIST_proc -s $APLI '/audio_platform_info/bit_width_configs/device[@name="SND_DEVICE_OUT_GAME_HEADPHONES"]' "24"
	AIST_proc -s $APLI '/audio_platform_info/bit_width_configs/device[@name="SND_DEVICE_OUT_BT_A2DP"]' "24"	 
	AIST_proc -u $APLI '/audio_platform_info/app_types/app[@mode="default"]' "bit_width=24"
	AIST_proc -u $APLI '/audio_platform_info/app_types/app[@mode="default"]' "max_rate=192000"
	AIST_proc -s $APLI '/audio_platform_info/app_types/app[@mode="default"]' "bit_width=24"
	AIST_proc -s $APLI '/audio_platform_info/app_types/app[@mode="default"]' "max_rate=192000"
	if [ ! "$(grep '<app_types>' $APLI)" ]; then
	sed -i "s/<\/audio_platform_info>/  <app_types> \n    <app uc_type=\"PCM_PLAYBACK\" mode=\"default\" bit_width=\"24\" id=\"69936\" max_rate=\"384000\" \/> \n    <app uc_type=\"PCM_PLAYBACK\" mode=\"default\" bit_width=\"24\" id=\"69940\" max_rate=\"384000\" \/> \n  <app_types> \n<\/audio_platform_info>/" $APLI
	sed -i "s/<\/audio_platform_info_intcodec>/  <app_types> \n    <app uc_type=\"PCM_PLAYBACK\" mode=\"default\" bit_width=\"24\" id=\"69936\" max_rate=\"384000\" \/> \n    <app uc_type=\"PCM_PLAYBACK\" mode=\"default\" bit_width=\"24\" id=\"69940\" max_rate=\"384000\" \/> \n  <app_types> \n<\/audio_platform_info_intcodec>/" $APLI		  
	sed -i "s/<\/audio_platform_info_extcodec>/  <app_types> \n    <app uc_type=\"PCM_PLAYBACK\" mode=\"default\" bit_width=\"24\" id=\"69936\" max_rate=\"384000\" \/> \n    <app uc_type=\"PCM_PLAYBACK\" mode=\"default\" bit_width=\"24\" id=\"69940\" max_rate=\"384000\" \/> \n  <app_types> \n<\/audio_platform_info_extcodec>/" $APLI		  
	else
	for i in 69936 69940; do
	[ "$(xmlstarlet sel -t -m "/audio_platform_info/app_types/app[@uc_type=\"PCM_PLAYBACK\"][@mode=\"default\"][@id=\"$i\"]" -c . $APLI)" ] || sed -i "/<audio_platform_info>/,/<\/audio_platform_info>/ {/<app_types>/,/<\/app_types>/ s/\(^ *\)\(<\/app_types>\)/\1  <app uc_type=\"PCM_PLAYBACK\" mode=\"default\" bit_width=\"24\" id=\"$i\" max_rate=\"384000\" \/> \n\1\2/}" $APLI
	[ "$(xmlstarlet sel -t -m "/audio_platform_info_intcodec/app_types/app[@uc_type=\"PCM_PLAYBACK\"][@mode=\"default\"][@id=\"$i\"]" -c . $APLI)" ] || sed -i "/<audio_platform_info_intcodec>/,/<\/audio_platform_info_intcodec>/ {/<app_types>/,/<\/app_types>/ s/\(^ *\)\(<\/app_types>\)/\1  <app uc_type=\"PCM_PLAYBACK\" mode=\"default\" bit_width=\"24\" id=\"$i\" max_rate=\"384000\" \/> \n\1\2/}" $APLI			
	[ "$(xmlstarlet sel -t -m "/audio_platform_info_extcodec/app_types/app[@uc_type=\"PCM_PLAYBACK\"][@mode=\"default\"][@id=\"$i\"]" -c . $APLI)" ] || sed -i "/<audio_platform_info_extcodec>/,/<\/audio_platform_info_extcodec>/ {/<app_types>/,/<\/app_types>/ s/\(^ *\)\(<\/app_types>\)/\1  <app uc_type=\"PCM_PLAYBACK\" mode=\"default\" bit_width=\"24\" id=\"$i\" max_rate=\"384000\" \/> \n\1\2/}" $APLI			
	done
	fi
	done

  for OACONF in ${ACONFS}; do
	ACONF="$MODPATH$(echo $OACONF | sed "s|^/vendor|/system/vendor|g")"
	cp_ch $ORIGDIR$OACONF $ACONF
	sed -i 's/\t/  /g' $ACONF
	AIST_proc -u $ACONF '/configs/property[@name="audio.offload.video"]' "true"
	AIST_proc -u $ACONF '/configs/property[@name="audio.deep_buffer.media"]' "true"
	AIST_proc -u $ACONF '/configs/property[@name="persist.vendor.audio.sva.conc.enabled"]' "false"
	AIST_proc -u $ACONF '/configs/property[@name="persist.vendor.audio.va_concurrency_enabled"]' "false"
	AIST_proc -u $ACONF '/configs/property[@name="vendor.voice.dsd.playback.conc.disabled"]' "true"
	AIST_proc -u $ACONF '/configs/property[@name="vendor.voice.playback.conc.disabled"]' "true"
	AIST_proc -u $ACONF '/configs/property[@name="vendor.audio.offload.track.enable"]' "true"
	AIST_proc -u $ACONF '/configs/property[@name="vendor.audio.offload.multiple.enabled"]' "false"
	AIST_proc -u $ACONF '/configs/property[@name="vendor.audio.av.streaming.offload.enable"]' "false"
	AIST_proc -u $ACONF '/configs/property[@name="vendor.audio.rec.playback.conc.disabled"]' "true"
	AIST_proc -u $ACONF '/configs/property[@name="vendor.voice.record.conc.disabled"]' "true"
	AIST_proc -u $ACONF '/configs/property[@name="vendor.voice.voip.conc.disabled"]' "true"
	AIST_proc -u $ACONF '/configs/property[@name="vendor.voice.path.for.pcm.voip"]' "true"
	AIST_proc -u $ACONF '/configs/property[@name="vendor.audio.use.sw.alac.decoder"]' "true"
	AIST_proc -u $ACONF '/configs/property[@name="vendor.audio.use.sw.ape.decoder"]' "true"
	AIST_proc -u $ACONF '/configs/property[@name="vendor.audio.use.sw.mpegh.decoder"]' "true"
	AIST_proc -u $ACONF '/configs/property[@name="vendor.audio.flac.sw.decoder.24bit"]' "true"
	AIST_proc -u $ACONF '/configs/property[@name="vendor.audio.hw.aac.encoder"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="a2dp_offload_enabled"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="anc_headset_enabled"]' "false"
	AIST_proc -u $ACONF '/configs/flag[@name="custom_stereo_enabled"]' "false"
	AIST_proc -u $ACONF '/configs/flag[@name="voice_concurrency"]' "false"
	AIST_proc -u $ACONF '/configs/flag[@name="compress_voip_enabled"]' "false"
	AIST_proc -u $ACONF '/configs/flag[@name="battery_listener_enabled"]' "false"
	AIST_proc -u $ACONF '/configs/flag[@name="compress_capture_enabled"]' "false"
	AIST_proc -u $ACONF '/configs/flag[@name="record_play_concurrency"]' "false"
	AIST_proc -u $ACONF '/configs/flag[@name="concurrent_capture_enabled"]' "false"
	AIST_proc -u $ACONF '/configs/flag[@name="aac_adts_offload_enabled"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="alac_offload_enabled"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="ape_offload_enabled"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="flac_offload_enabled"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="pcm_offload_enabled_16"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="pcm_offload_enabled_24"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="qti_flac_decoder"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="vorbis_offload_enabled"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="wma_offload_enabled"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="audio_zoom_enabled"]' "false"
	AIST_proc -u $ACONF '/configs/flag[@name="audiosphere_enabled"]' "false"
	AIST_proc -u $ACONF '/configs/flag[@name="ext_hw_plugin_enabled"]' "false"
	AIST_proc -u $ACONF '/configs/flag[@name="ext_qdsp_enabled"]' "false"
	AIST_proc -u $ACONF '/configs/flag[@name="ext_spkr_enabled"]' "false"
	AIST_proc -u $ACONF '/configs/flag[@name="ext_spkr_tfa_enabled"]' "false"
	AIST_proc -u $ACONF '/configs/flag[@name="receiver_aided_stereo"]' "false"
	AIST_proc -u $ACONF '/configs/flag[@name="hfp_enabled"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="hifi_audio_enabled"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="hwdep_cal_enabled"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="multi_voice_session"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="maxx_audio_enabled"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="usb_offload_burst_mode"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="usb_offload_enabled"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="usb_offload_sidetone_vol_enabled"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="keep_alive_enabled"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="kpi_optimize_enabled"]' "true"
	AIST_proc -u $ACONF '/configs/flag[@name="spkr_prot_enabled"]' "false"
	AIST_proc -u $ACONF '/configs/flag[@name="vbat_enabled"]' "false"
	AIST_proc -u $ACONF '/configs/flag[@name="snd_monitor_enabled"]' "false"
	done

  for OAPCXM in ${APCXML}; do
	APCXM="$MODPATH$(echo $OAPCXM | sed "s|^/vendor|/system/vendor|g")"
	cp_ch $ORIGDIR$OAPCXM $APCXM
	sed -i 's/\t/  /g' $APCXM
	sed -i 's/speaker_drc_enabled="true"/speaker_drc_enabled="false"/g' $APCXM
	done
